// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForBulkInsertPriceSnapshots implements pgx.CopyFromSource.
type iteratorForBulkInsertPriceSnapshots struct {
	rows                 []BulkInsertPriceSnapshotsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertPriceSnapshots) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertPriceSnapshots) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].PoolAddress,
		r.rows[0].Token0Address,
		r.rows[0].Token1Address,
		r.rows[0].SqrtPriceX96,
		r.rows[0].Tick,
		r.rows[0].Liquidity,
		r.rows[0].Token0Price,
		r.rows[0].Token1Price,
	}, nil
}

func (r iteratorForBulkInsertPriceSnapshots) Err() error {
	return nil
}

func (q *Queries) BulkInsertPriceSnapshots(ctx context.Context, arg []BulkInsertPriceSnapshotsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"price_snapshots"}, []string{"pool_address", "token0_address", "token1_address", "sqrt_price_x96", "tick", "liquidity", "token0_price", "token1_price"}, &iteratorForBulkInsertPriceSnapshots{rows: arg})
}
