// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddMonitoredPool(ctx context.Context, arg AddMonitoredPoolParams) (uuid.UUID, error)
	BulkInsertPriceSnapshots(ctx context.Context, arg []BulkInsertPriceSnapshotsParams) (int64, error)
	GetLatestPositionSnapshots(ctx context.Context, dollar_1 []string) ([]PositionSnapshots, error)
	GetLatestPriceByPool(ctx context.Context, poolAddress string) (GetLatestPriceByPoolRow, error)
	GetLatestVolatility(ctx context.Context, arg GetLatestVolatilityParams) (GetLatestVolatilityRow, error)
	GetMonitoredPools(ctx context.Context) ([]GetMonitoredPoolsRow, error)
	GetPositionHistory(ctx context.Context, arg GetPositionHistoryParams) ([]GetPositionHistoryRow, error)
	GetPositionsNearRangeEdge(ctx context.Context, rangePercentage pgtype.Numeric) ([]GetPositionsNearRangeEdgeRow, error)
	GetPositionsOutOfRange(ctx context.Context) ([]GetPositionsOutOfRangeRow, error)
	GetPriceHistory(ctx context.Context, arg GetPriceHistoryParams) ([]GetPriceHistoryRow, error)
	GetVolatilityHistory(ctx context.Context, arg GetVolatilityHistoryParams) ([]GetVolatilityHistoryRow, error)
	InsertPositionSnapshot(ctx context.Context, arg InsertPositionSnapshotParams) (InsertPositionSnapshotRow, error)
	InsertPriceSnapshot(ctx context.Context, arg InsertPriceSnapshotParams) (InsertPriceSnapshotRow, error)
	InsertVolatilityMetric(ctx context.Context, arg InsertVolatilityMetricParams) (InsertVolatilityMetricRow, error)
}

var _ Querier = (*Queries)(nil)
