apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yield-optimizer.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yield-optimizer.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.monitor.secretEnv.DATABASE_URL }}
  DATABASE_URL: {{ .Values.monitor.secretEnv.DATABASE_URL | b64enc }}
  {{- end }}
  {{- if .Values.monitor.secretEnv.REDIS_URL }}
  REDIS_URL: {{ .Values.monitor.secretEnv.REDIS_URL | b64enc }}
  {{- end }}
  {{- if .Values.monitor.secretEnv.POSITION_MANAGER_ADDRESS }}
  POSITION_MANAGER_ADDRESS: {{ .Values.monitor.secretEnv.POSITION_MANAGER_ADDRESS | b64enc }}
  {{- end }}
  {{- if .Values.monitor.secretEnv.VAULT_ADDRESSES }}
  VAULT_ADDRESSES: {{ .Values.monitor.secretEnv.VAULT_ADDRESSES | b64enc }}
  {{- end }}