{{- if and .Values.monitor.enabled .Values.monitor.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "yield-optimizer.fullname" . }}-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yield-optimizer.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitor
spec:
  selector:
    matchLabels:
      {{- include "yield-optimizer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: monitor
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
{{- end }}