package main

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	// Position metrics
	positionsTotal = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "yield_optimizer_positions_total",
		Help: "Total number of active positions",
	}, []string{"vault", "status"})

	positionValue = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "yield_optimizer_position_value_usd",
		Help: "Current value of positions in USD",
	}, []string{"vault", "token"})

	// APY metrics
	currentAPY = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "yield_optimizer_apy_current",
		Help: "Current APY percentage for each vault",
	}, []string{"vault"})

	historicalAPY = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "yield_optimizer_apy_historical",
		Help:    "Historical APY distribution",
		Buckets: prometheus.LinearBuckets(0, 5, 20), // 0-100% in 5% increments
	}, []string{"vault"})

	// Rebalancing metrics
	rebalancesTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "yield_optimizer_rebalances_total",
		Help: "Total number of rebalances performed",
	}, []string{"status", "vault"})

	rebalanceDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "yield_optimizer_rebalance_duration_seconds",
		Help:    "Time taken to complete a rebalance",
		Buckets: prometheus.ExponentialBuckets(1, 2, 10), // 1s to ~1024s
	}, []string{"vault"})

	gasUsed = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "yield_optimizer_gas_used_total",
		Help: "Total gas used for transactions",
	}, []string{"operation", "vault"})

	// Error metrics
	errorsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "yield_optimizer_errors_total",
		Help: "Total number of errors",
	}, []string{"error_type", "operation"})

	// Database metrics
	dbConnectionsActive = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "yield_optimizer_database_connections_active",
		Help: "Number of active database connections",
	})

	dbQueriesTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "yield_optimizer_database_queries_total",
		Help: "Total number of database queries",
	}, []string{"query_type", "status"})

	dbQueryDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "yield_optimizer_database_query_duration_seconds",
		Help:    "Database query duration",
		Buckets: prometheus.ExponentialBuckets(0.001, 2, 10), // 1ms to ~1s
	}, []string{"query_type"})

	// Price feed metrics
	priceUpdatesTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "yield_optimizer_price_updates_total",
		Help: "Total number of price updates",
	}, []string{"token", "source"})

	priceUpdateLatency = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "yield_optimizer_price_update_latency_seconds",
		Help:    "Time since last price update",
		Buckets: prometheus.ExponentialBuckets(1, 2, 10),
	}, []string{"token"})

	currentPrice = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "yield_optimizer_token_price_usd",
		Help: "Current token price in USD",
	}, []string{"token"})

	// Strategy metrics
	strategyExecutions = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "yield_optimizer_strategy_executions_total",
		Help: "Total number of strategy executions",
	}, []string{"strategy", "result"})

	strategyProfit = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "yield_optimizer_strategy_profit_usd",
		Help: "Profit generated by strategy in USD",
	}, []string{"strategy", "period"})

	// Chain metrics
	blockNumber = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "yield_optimizer_chain_block_number",
		Help: "Current block number being processed",
	})

	blockProcessingTime = promauto.NewHistogram(prometheus.HistogramOpts{
		Name:    "yield_optimizer_block_processing_seconds",
		Help:    "Time taken to process a block",
		Buckets: prometheus.ExponentialBuckets(0.01, 2, 10),
	})

	// Contract interaction metrics
	contractCallsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "yield_optimizer_contract_calls_total",
		Help: "Total number of contract calls",
	}, []string{"contract", "method", "status"})

	contractCallDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "yield_optimizer_contract_call_duration_seconds",
		Help:    "Duration of contract calls",
		Buckets: prometheus.ExponentialBuckets(0.1, 2, 10),
	}, []string{"contract", "method"})

	// Health check metrics
	healthCheckStatus = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "yield_optimizer_health_check_status",
		Help: "Health check status (1 = healthy, 0 = unhealthy)",
	}, []string{"component"})

	lastHealthCheckTimestamp = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "yield_optimizer_health_check_timestamp",
		Help: "Timestamp of last health check",
	}, []string{"component"})
)

// MetricsCollector handles custom metrics collection
type MetricsCollector struct {
	monitor *Monitor
}

// NewMetricsCollector creates a new metrics collector
func NewMetricsCollector(monitor *Monitor) *MetricsCollector {
	return &MetricsCollector{
		monitor: monitor,
	}
}

// UpdatePositionMetrics updates position-related metrics
func (mc *MetricsCollector) UpdatePositionMetrics(positions []Position) {
	vaultCounts := make(map[string]int)
	vaultValues := make(map[string]float64)

	for _, pos := range positions {
		vaultCounts[pos.Vault]++
		vaultValues[pos.Vault] += pos.ValueUSD
		
		positionValue.WithLabelValues(pos.Vault, pos.Token).Set(pos.ValueUSD)
	}

	for vault, count := range vaultCounts {
		positionsTotal.WithLabelValues(vault, "active").Set(float64(count))
	}
}

// UpdateAPYMetrics updates APY-related metrics
func (mc *MetricsCollector) UpdateAPYMetrics(vault string, apy float64) {
	currentAPY.WithLabelValues(vault).Set(apy)
	historicalAPY.WithLabelValues(vault).Observe(apy)
}

// RecordRebalance records a rebalance event
func (mc *MetricsCollector) RecordRebalance(vault string, success bool, duration float64) {
	status := "success"
	if !success {
		status = "failed"
	}
	
	rebalancesTotal.WithLabelValues(status, vault).Inc()
	if success {
		rebalanceDuration.WithLabelValues(vault).Observe(duration)
	}
}

// RecordError records an error
func (mc *MetricsCollector) RecordError(errorType, operation string) {
	errorsTotal.WithLabelValues(errorType, operation).Inc()
}

// RecordGasUsage records gas usage
func (mc *MetricsCollector) RecordGasUsage(operation, vault string, gas float64) {
	gasUsed.WithLabelValues(operation, vault).Add(gas)
}

// UpdateDatabaseMetrics updates database-related metrics
func (mc *MetricsCollector) UpdateDatabaseMetrics(activeConnections int) {
	dbConnectionsActive.Set(float64(activeConnections))
}

// RecordDatabaseQuery records a database query
func (mc *MetricsCollector) RecordDatabaseQuery(queryType string, success bool, duration float64) {
	status := "success"
	if !success {
		status = "failed"
	}
	
	dbQueriesTotal.WithLabelValues(queryType, status).Inc()
	if success {
		dbQueryDuration.WithLabelValues(queryType).Observe(duration)
	}
}

// UpdatePriceMetrics updates price-related metrics
func (mc *MetricsCollector) UpdatePriceMetrics(token string, price float64, source string) {
	currentPrice.WithLabelValues(token).Set(price)
	priceUpdatesTotal.WithLabelValues(token, source).Inc()
}

// RecordStrategyExecution records a strategy execution
func (mc *MetricsCollector) RecordStrategyExecution(strategy string, success bool, profit float64) {
	result := "success"
	if !success {
		result = "failed"
	}
	
	strategyExecutions.WithLabelValues(strategy, result).Inc()
	if success && profit > 0 {
		strategyProfit.WithLabelValues(strategy, "session").Set(profit)
	}
}

// UpdateBlockMetrics updates blockchain-related metrics
func (mc *MetricsCollector) UpdateBlockMetrics(blockNum uint64, processingTime float64) {
	blockNumber.Set(float64(blockNum))
	blockProcessingTime.Observe(processingTime)
}

// RecordContractCall records a smart contract interaction
func (mc *MetricsCollector) RecordContractCall(contract, method string, success bool, duration float64) {
	status := "success"
	if !success {
		status = "failed"
	}
	
	contractCallsTotal.WithLabelValues(contract, method, status).Inc()
	if success {
		contractCallDuration.WithLabelValues(contract, method).Observe(duration)
	}
}

// UpdateHealthStatus updates health check status
func (mc *MetricsCollector) UpdateHealthStatus(component string, healthy bool, timestamp float64) {
	status := float64(0)
	if healthy {
		status = 1
	}
	
	healthCheckStatus.WithLabelValues(component).Set(status)
	lastHealthCheckTimestamp.WithLabelValues(component).Set(timestamp)
}